### ISSUE TITLE
In modern DRF CurrentUserDefault might be used instead of custom mixing Please mind the properties naming (course root)

### ISSUE THREAD

**Issue by stl-pavelsushko** [business-maksim-duksin/djangoTrainingPlatform#3]

**Comment by business-maksim-duksin** [comment]
Due to https://github.com/encode/django-rest-framework/pull/5886 i had two ways of associating objects with users:

1. Overwrite Serializer's save().
2. Use perform_create() at the view level.

Docs recommend 2. https://www.django-rest-framework.org/tutorial/4-authentication-and-permissions/#associating-snippets-with-users.


Properties naming fixed in 4a9f6354a0154080960272836c0fbf69ec26d86f.
